### ISSUE TITLE
Solving the Structure from Motion Problem

### ISSUE THREAD

**Issue by mirkosprojects** [mirkosprojects/MeshroomDFM#1]
With the current implementation of the DFM Node, the pipeline fails at the Structure from Motion Node.
This topic has been opened as a discussion in the Meshroom repository and can be found [here][sfm-error-question].

A possible first step to solve this problem has been proposed in the [Conclusion of the Wiki](https://github.com/mirkosprojects/MeshroomDFM/wiki/Conclusion#solving-the-structure-from-motion-problem).

> ### Solving the Structure from Motion Problem
> The error logs of the structure from motion node can be found in a [discussion][sfm-error-question], that I started to the meshroom forums. Here, someone suggested to take a look at the source code of the structure from motion node, specifically at the [fuseMatchesIntoTracks][fuse-matches-url] function. 
A first look into the source code reveals, that SfM fails at the [computePyramidPerView][compute-pyramid-url] function, which could rely on the descriptors being present in the same directory as the features.

[sfm-error-question]: https://github.com/alicevision/Meshroom/discussions/2130
[fuse-matches-url]: https://github.com/alicevision/AliceVision/blob/271ac7a39db0bcb2456a34be899a528097a59ef0/src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.cpp#L243
[compute-pyramid-url]: https://github.com/alicevision/AliceVision/blob/271ac7a39db0bcb2456a34be899a528097a59ef0/src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.cpp#L69
[loftr-paper]: https://doi.org/10.48550/arXiv.2104.00680

**Comment by vintheruler1** [comment]
Any updates on this? Trying to use this too but encountered the same issue.

**Comment by fabiencastan** [comment]
The computePyramidPerView function does not rely on the descriptors.

**Comment by vintheruler1** [comment]
[3464] Failed to execute script 'dfm_wrapper' due to unhandled exception!
Traceback (most recent call last):
  File "dfm_wrapper.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "utils\DeepFeatureMatcher.py", line 9, in <module>
ImportError: DLL load failed: The specified module could not be found.

I am actively working on trying to fix this error. Not exactly sure where the computePyramidPerView comes into play here.

**Comment by mirkosprojects** [comment]
> Any updates on this? Trying to use this too but encountered the same issue.

I'm not currently working on this project, so there aren't any fixes for the problem yet.
I hope, that other students will pick it up though.
